Repository realchillguyclub/legacy-backend, pull requests merged in 2025-03, with the labels that each got.

#56 [feat] : fcm토큰과 관련된 문제를 해결한다
  src/main/java/server/poptato/auth/api/AuthController.java
  src/main/java/server/poptato/auth/api/request/FCMTokenRequestDto.java
  src/main/java/server/poptato/auth/api/request/LoginRequestDto.java
  src/main/java/server/poptato/auth/api/request/ReissueTokenRequestDto.java
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/test/java/server/poptato/auth/api/AuthControllerTest.java
Labels: 🚀 feat, 😄 JAEWOONG

#59 [feat] : 백로그 조회 시 YESTERDAY 타입은 제외한다
  src/main/java/server/poptato/todo/application/TodoBacklogService.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
Labels: 🚀 feat, 😵‍💫 SANGHO

#60 [feat] : 배포 후 미사용 Docker 이미지를 정리하여 리소스를 최적화한다
  deploy/deploy.sh
Labels: 🚀 feat, 😵‍💫 SANGHO

#63 [feat] : 환경 별 yaml 파일을 분리하고, 테스트 환경에서는 스케줄러가 돌아가지 않도록 설정한다
  .github/workflows/prod-cicd.yaml
  .github/workflows/test-cicd.yaml
  src/main/java/server/poptato/external/firebase/service/FcmNotificationScheduler.java
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 😵‍💫 SANGHO

#65 [feat] : 투두 스케줄러의 제한을 제거한다
  src/main/java/server/poptato/todo/application/TodoScheduler.java
Labels: 🚀 feat, 😵‍💫 SANGHO

#67 [feat] : 카테고리 예외 처리 문제를 해결한다
  src/main/java/server/poptato/category/validator/CategoryValidator.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#70 [fix] : 어제 한 일 체크 이후 반복 할 일 새 객체를 만드는 과정에서 누락된 중요 표시와 백로그 순서를 추가한다
  src/main/java/server/poptato/category/application/CategoryService.java
  src/main/java/server/poptato/todo/application/TodoService.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#73 [fix] : clientId로 Mobile삭제시 Transactional을 적용한다 (#72)
  src/main/java/server/poptato/user/infra/repository/JpaMobileRepository.java
Labels: 🚀 feat, 🚨 fix, 😄 JAEWOONG

#75 [fix] : Swagger 스키마 미적용 문제를 해결한다
  src/main/java/server/poptato/global/config/SwaggerConfig.java
Labels: 🚨 fix, 😵‍💫 SANGHO
