Repository realchillguyclub/legacy-backend, pull requests merged in 2025-02, with the labels that each got.

#18 [feat] : 액세스 & 리프레쉬 토큰 에러 응답을 구분한다
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/prod-cicd.yaml
  .github/workflows/test-cicd.yaml
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/auth/application/service/JwtService.java
  src/main/java/server/poptato/auth/status/AuthErrorStatus.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 😵‍💫 SANGHO, 🌱 style

#22 [fix] : 마감 기한의 null을 허용하여 문제를 해결한다
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  src/main/java/server/poptato/todo/api/request/DeadlineUpdateRequestDto.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO, 🌱 style

#24 [fix] : 완료 -> 미완료로 변경하는 로직을 복원한다
  src/main/java/server/poptato/todo/application/TodoService.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#27 [fix] : 기한 유효성 검사 시, 당일까지 포함하도록 변경한다
  src/main/java/server/poptato/todo/api/request/DeadlineUpdateRequestDto.java
Labels: 🚨 fix, 😵‍💫 SANGHO

#16 [feat] : Apple 소셜 로그인을 구현한다
  src/main/java/server/poptato/auth/api/request/LoginRequestDto.java
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/auth/status/AuthErrorStatus.java
  src/main/java/server/poptato/external/oauth/SocialService.java
  src/main/java/server/poptato/external/oauth/SocialUserInfo.java
  src/main/java/server/poptato/external/oauth/apple/AppleApiClient.java
  src/main/java/server/poptato/external/oauth/apple/AppleSocialService.java
  src/main/java/server/poptato/external/oauth/apple/AppleTokenVerifier.java
  src/main/java/server/poptato/external/oauth/kakao/KakaoSocialService.java
  src/main/java/server/poptato/global/config/FeignConfig.java
  src/main/java/server/poptato/user/domain/entity/Mobile.java
  src/main/java/server/poptato/user/domain/entity/User.java
  src/test/java/server/poptato/auth/api/AuthControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO, 🌱 style

#34 [fix] : 할 일 드래그앤드롭에서 삭제된 로직을 복구하고, 정렬을 역순으로 변경한다
  src/main/java/server/poptato/todo/application/TodoService.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#33 [fix] : 사용자 탈퇴시 DB에서 삭제가 되도록 한다
  .github/workflows/test-cicd.yaml
  src/main/java/server/poptato/category/domain/repository/CategoryRepository.java
  src/main/java/server/poptato/user/application/service/UserService.java
  src/main/resources/application.yaml
Labels: 🚨 fix, 😄 JAEWOONG

#38 [chore] : application.yaml 파일을 추가한다
  src/main/resources/application.yaml
Labels: ⚒️ chore, 😵‍💫 SANGHO

#29 [feat] : 마감기한 당일이 되면 자동으로 오늘 할 일로 넘어가도록 수정한다
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/main/java/server/poptato/user/domain/repository/UserRepository.java
  src/main/java/server/poptato/user/infra/repository/JpaUserRepository.java
Labels: 🚀 feat, 😄 JAEWOONG

#48 [feat] : fcm토큰 중 한 달 이상 timestamp가 갱신이 되지 않은 토큰을 삭제한다 (#47)
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/user/domain/repository/MobileRepository.java
  src/main/java/server/poptato/user/infra/repository/JpaMobileRepository.java
Labels: 🚀 feat, 😄 JAEWOONG

#49 [feat] : 어제 못 한 일은 백로그 가장 위에 쌓이도록 변경하고, 푸쉬알림의 형태를 수정한다
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
Labels: 🚀 feat, 😵‍💫 SANGHO, 🌱 style

#51 [refactor] : 스케줄러 코드를 리팩토링하고 여러 문제를 해결한다
  src/main/java/server/poptato/auth/application/service/JwtService.java
  src/main/java/server/poptato/auth/status/AuthErrorStatus.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationService.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/request/CheckYesterdayTodosRequestDto.java
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/main/java/server/poptato/user/domain/repository/MobileRepository.java
  src/main/java/server/poptato/user/infra/repository/JpaMobileRepository.java
  src/main/resources/application.yaml
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 🚨 fix, 🔄 refactor, 😵‍💫 SANGHO
