Repository realchillguyclub/legacy-backend, pull requests merged in 2025-04, with the labels that each got.

#77 [feat] : 기록 페이지에 마감기한이 정해진 할일이 보이도록 구현한다
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarListResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryResponseDto.java
  src/main/java/server/poptato/todo/application/response/PaginatedHistoryResponseDto.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 😄 JAEWOONG

#78 [feat] : 날짜 목록을 오름차순 정렬하여 반환한다
  src/main/java/server/poptato/todo/application/response/HistoryCalendarListResponseDto.java
Labels: 🚀 feat, 😵‍💫 SANGHO

#80 [feat] : API 버저닝 및 도커 빌드 캐시 파일을 정리한다
  deploy/deploy.sh
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#82 [feat] : 오늘, 할일 페이지에 카테고리 정보를 추가한다
  src/main/java/server/poptato/category/api/CategoryController.java
  src/main/java/server/poptato/category/domain/entity/Category.java
  src/main/java/server/poptato/emoji/api/controller/EmojiController.java
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/resolver/MobileTypeArgumentResolver.java
  src/main/java/server/poptato/global/response/status/ErrorStatus.java
  src/main/java/server/poptato/todo/api/TodoBacklogController.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/TodoTodayController.java
  src/main/java/server/poptato/todo/application/TodoBacklogService.java
  src/main/java/server/poptato/todo/application/TodoTodayService.java
  src/main/java/server/poptato/todo/application/response/BacklogListResponseDto.java
  src/main/java/server/poptato/todo/application/response/BacklogResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayListResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayResponseDto.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/test/java/server/poptato/category/api/CategoryControllerTest.java
  src/test/java/server/poptato/emoji/api/EmojiControllerTest.java
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 🚀 feat, 😄 JAEWOONG

#84 [feat] : 앱 버전 리졸버를 추가하고, 버저닝 방식을 수정한다
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/resolver/AppVersionArgumentResolver.java
  src/main/java/server/poptato/global/resolver/MobileTypeArgumentResolver.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarListResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarResponseDto.java
  src/main/java/server/poptato/todo/application/response/LegacyHistoryCalendarResponseDto.java
  src/main/java/server/poptato/todo/domain/value/AppVersion.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 😵‍💫 SANGHO

#86 [feat] : 리졸버 제거 및 변수명을 일부 수정한다
  src/main/java/server/poptato/category/api/CategoryController.java
  src/main/java/server/poptato/emoji/api/controller/EmojiController.java
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/resolver/AppVersionArgumentResolver.java
  src/main/java/server/poptato/global/resolver/MobileTypeArgumentResolver.java
  src/main/java/server/poptato/todo/api/TodoBacklogController.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/TodoTodayController.java
  src/main/java/server/poptato/todo/api/request/DeadlineUpdateRequestDto.java
  src/main/java/server/poptato/todo/application/response/BacklogResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayListResponseDto.java
  src/main/java/server/poptato/todo/domain/value/AppVersion.java
  src/main/java/server/poptato/user/api/UserController.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
Labels: 🚀 feat, 🔄 refactor, ✂️ remove, 😵‍💫 SANGHO, 🌱 style

#87 [release] : v1.0.2
  deploy/deploy.sh
  src/main/java/server/poptato/category/api/CategoryController.java
  src/main/java/server/poptato/category/domain/entity/Category.java
  src/main/java/server/poptato/emoji/api/controller/EmojiController.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationScheduler.java
  src/main/java/server/poptato/global/config/SwaggerConfig.java
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/response/status/ErrorStatus.java
  src/main/java/server/poptato/todo/api/TodoBacklogController.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/TodoTodayController.java
  src/main/java/server/poptato/todo/api/request/DeadlineUpdateRequestDto.java
  src/main/java/server/poptato/todo/application/TodoBacklogService.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/application/TodoTodayService.java
  src/main/java/server/poptato/todo/application/response/BacklogListResponseDto.java
  src/main/java/server/poptato/todo/application/response/BacklogResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarListResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryCalendarResponseDto.java
  src/main/java/server/poptato/todo/application/response/HistoryResponseDto.java
  src/main/java/server/poptato/todo/application/response/LegacyHistoryCalendarResponseDto.java
  src/main/java/server/poptato/todo/application/response/PaginatedHistoryResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayListResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayResponseDto.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/domain/value/AppVersion.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/main/java/server/poptato/user/api/UserController.java
  src/test/java/server/poptato/category/api/CategoryControllerTest.java
  src/test/java/server/poptato/emoji/api/EmojiControllerTest.java
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 💫 release

#90 [feat] : swagger와 관련된 테스트코드를 추가한다.
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 🚀 feat, 😄 JAEWOONG

#91 [feat] : 하루 시작 & 일과 정리 푸쉬 알림 기능을 구현한다
  deploy/deploy.sh
  src/main/java/server/poptato/external/firebase/application/FcmNotificationBatchService.java
  src/main/java/server/poptato/external/firebase/application/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/application/FcmService.java
  src/main/java/server/poptato/external/firebase/application/FcmTokenService.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationService.java
  src/main/java/server/poptato/external/firebase/template/FcmNotificationTemplate.java
  src/main/java/server/poptato/global/util/BatchUtil.java
  src/main/java/server/poptato/todo/application/TodoBatchService.java
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/user/domain/repository/UserRepository.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 🔄 refactor, 😵‍💫 SANGHO

#92 [release] : v1.0.3
  deploy/deploy.sh
  src/main/java/server/poptato/external/firebase/application/FcmNotificationBatchService.java
  src/main/java/server/poptato/external/firebase/application/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/application/FcmService.java
  src/main/java/server/poptato/external/firebase/application/FcmTokenService.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/service/FcmNotificationService.java
  src/main/java/server/poptato/external/firebase/template/FcmNotificationTemplate.java
  src/main/java/server/poptato/global/util/BatchUtil.java
  src/main/java/server/poptato/todo/application/TodoBatchService.java
  src/main/java/server/poptato/todo/application/TodoScheduler.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/user/domain/repository/UserRepository.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 💫 release
