Repository realchillguyclub/legacy-backend, pull requests merged in 2025-05, with the labels that each got.

#94 [remove] : 이용 가이드 문구와 추가 로직을 제거한다
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/todo/constant/TutorialMessage.java
Labels: 🚀 feat, ✂️ remove, 😵‍💫 SANGHO

#95 [release] : v1.0.4
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/todo/constant/TutorialMessage.java
Labels: 💫 release

#99 [feat] : 어제 백로그를 생성할 수 있다
  src/main/java/server/poptato/todo/api/TodoBacklogController.java
  src/main/java/server/poptato/todo/application/TodoBacklogService.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
Labels: 🚀 feat, 😵‍💫 SANGHO

#100 [release] : v1.0.5
  src/main/java/server/poptato/external/firebase/application/FcmNotificationBatchService.java
  src/main/java/server/poptato/todo/api/TodoBacklogController.java
  src/main/java/server/poptato/todo/application/TodoBacklogService.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
Labels: 💫 release

#102 [feat] : 시간 설정 기능을 구현한다
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/request/TimeUpdateRequestDto.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/application/response/BacklogResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodoDetailResponseDto.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 🚀 feat, 😄 JAEWOONG

#105 [feat] : 로깅을 개선한다
  .github/workflows/test-cicd.yaml
  src/main/java/server/poptato/global/config/SwaggerConfig.java
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/exception/GlobalExceptionHandler.java
  src/main/java/server/poptato/global/filter/RequestWrapperFilter.java
  src/main/java/server/poptato/global/interceptor/LoggingInterceptor.java
  src/main/java/server/poptato/global/response/ApiResponse.java
  src/main/java/server/poptato/global/wrapper/CustomHttpRequestWrapper.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 😵‍💫 SANGHO

#107 [feat] : 도커 네트워크를 구성한다
  Dockerfile
  deploy/deploy.sh
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 😵‍💫 SANGHO

#108 [release] : v1.0.6
  .github/workflows/test-cicd.yaml
  Dockerfile
  deploy/deploy.sh
  src/main/java/server/poptato/global/config/SwaggerConfig.java
  src/main/java/server/poptato/global/config/WebConfig.java
  src/main/java/server/poptato/global/exception/GlobalExceptionHandler.java
  src/main/java/server/poptato/global/filter/RequestWrapperFilter.java
  src/main/java/server/poptato/global/interceptor/LoggingInterceptor.java
  src/main/java/server/poptato/global/response/ApiResponse.java
  src/main/java/server/poptato/global/wrapper/CustomHttpRequestWrapper.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/api/request/TimeUpdateRequestDto.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/application/response/BacklogResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodayResponseDto.java
  src/main/java/server/poptato/todo/application/response/TodoDetailResponseDto.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/test/java/server/poptato/todo/api/TodoBacklogControllerTest.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/todo/api/TodoTodayControllerTest.java
Labels: 💫 release

#110 [feat] : 엔터티 코드를 정리하고 불필요한 도메인 & 필드들을 제거한다
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/category/application/CategoryService.java
  src/main/java/server/poptato/category/domain/entity/Category.java
  src/main/java/server/poptato/category/domain/repository/CategoryRepository.java
  src/main/java/server/poptato/category/infra/JpaCategoryRepository.java
  src/main/java/server/poptato/emoji/application/service/EmojiService.java
  src/main/java/server/poptato/emoji/domain/entity/Emoji.java
  src/main/java/server/poptato/emoji/domain/repository/EmojiRepository.java
  src/main/java/server/poptato/emoji/infra/JpaEmojiRepository.java
  src/main/java/server/poptato/global/dao/BaseEntity.java
  src/main/java/server/poptato/policy/application/PolicyService.java
  src/main/java/server/poptato/policy/application/response/PolicyResponseDto.java
  src/main/java/server/poptato/policy/domain/entity/Policy.java
  src/main/java/server/poptato/policy/domain/repository/PolicyRepository.java
  src/main/java/server/poptato/policy/domain/value/Policy.java
  src/main/java/server/poptato/policy/infra/repository/JpaPolicyRepository.java
  src/main/java/server/poptato/todo/api/TodoController.java
  src/main/java/server/poptato/todo/application/TodoBatchService.java
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/application/TodoTodayService.java
  src/main/java/server/poptato/todo/domain/entity/CompletedDateTime.java
  src/main/java/server/poptato/todo/domain/entity/Todo.java
  src/main/java/server/poptato/todo/domain/repository/CompletedDateTimeRepository.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaCompletedDateTimeRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/main/java/server/poptato/user/domain/entity/DeleteReason.java
  src/main/java/server/poptato/user/domain/entity/Mobile.java
  src/main/java/server/poptato/user/domain/entity/User.java
  src/main/java/server/poptato/user/domain/repository/DeleteReasonRepository.java
  src/main/java/server/poptato/user/domain/repository/MobileRepository.java
  src/main/java/server/poptato/user/infra/repository/JpaMobileRepository.java
  src/main/java/server/poptato/user/infra/repository/JpaUserRepository.java
  src/test/java/server/poptato/todo/api/TodoControllerTest.java
  src/test/java/server/poptato/user/api/UserControllerTest.java
Labels: 🚀 feat, ✂️ remove, 😵‍💫 SANGHO

#117 [feat] : PR 라벨러 및 CODEOWNERS를 지정한다
  .github/CODEOWNERS
  .github/auto_assign.yaml
  .github/workflows/commit-labeler.yaml
Labels: 🚀 feat
