Repository realchillguyclub/legacy-backend, pull requests merged in 2025-08, with the labels that each got.

#135 [feat] : 유저 의견 보내기 & 가입 시 전송되는 메시지에 기기 정보를 추가한다 / 유저 탈퇴 시, 사유를 메세지로 전송한다
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/external/discord/client/DiscordDeleteUserWebhookClient.java
  src/main/java/server/poptato/external/discord/formatter/DiscordMessageFormatter.java
  src/main/java/server/poptato/external/discord/sender/DiscordSender.java
  src/main/java/server/poptato/external/notion/formatter/NotionPayloadFormatter.java
  src/main/java/server/poptato/external/notion/sender/NotionSender.java
  src/main/java/server/poptato/user/application/event/CreateUserCommentEvent.java
  src/main/java/server/poptato/user/application/event/CreateUserEvent.java
  src/main/java/server/poptato/user/application/event/DeleteUserEvent.java
  src/main/java/server/poptato/user/application/listener/UserEventListener.java
  src/main/java/server/poptato/user/application/service/UserService.java
  src/main/java/server/poptato/user/domain/repository/MobileRepository.java
  src/main/java/server/poptato/user/status/MobileErrorStatus.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#139 [release] : v1.0.9
  .github/workflows/sonarcloud.yml
  .github/workflows/test-cicd.yaml
  build.gradle
  src/main/java/server/poptato/auth/application/service/AuthService.java
  src/main/java/server/poptato/external/discord/client/DiscordDeleteUserWebhookClient.java
  src/main/java/server/poptato/external/discord/formatter/DiscordMessageFormatter.java
  src/main/java/server/poptato/external/discord/sender/DiscordSender.java
  src/main/java/server/poptato/external/notion/formatter/NotionPayloadFormatter.java
  src/main/java/server/poptato/external/notion/sender/NotionSender.java
  src/main/java/server/poptato/user/application/event/CreateUserCommentEvent.java
  src/main/java/server/poptato/user/application/event/CreateUserEvent.java
  src/main/java/server/poptato/user/application/event/DeleteUserEvent.java
  src/main/java/server/poptato/user/application/listener/UserEventListener.java
  src/main/java/server/poptato/user/application/service/UserService.java
  src/main/java/server/poptato/user/domain/repository/MobileRepository.java
  src/main/java/server/poptato/user/status/MobileErrorStatus.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 💫 release

#142 [test] : Policy와 관련된 서비스 로직 테스트를 작성한다
  .github/PULL_REQUEST_TEMPLATE.md
  src/test/java/server/poptato/policy/application/PolicyServiceTest.java
Labels: 📄 docs, 😄 JAEWOONG, ✅ test

#145 ILLDAN-150 [feat] : 미완료된 '오늘 할 일'에 푸쉬 알림을 전송한다
  src/main/java/server/poptato/external/firebase/application/FcmNotificationBatchService.java
  src/main/java/server/poptato/external/firebase/application/FcmNotificationScheduler.java
  src/main/java/server/poptato/external/firebase/template/FcmNotificationTemplate.java
  src/main/java/server/poptato/todo/domain/repository/TodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaTodoRepository.java
  src/main/java/server/poptato/todo/infra/repository/impl/TodoRepositoryImpl.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
Labels: 🚀 feat, 😵‍💫 SANGHO

#144 ILLDAN-140 [feat] : 달력에 요일 반복 todo도 노출한다
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/main/java/server/poptato/todo/application/TodoService.java
  src/main/java/server/poptato/todo/domain/projection/RoutineCountProjection.java
  src/main/java/server/poptato/todo/domain/repository/RoutineRepository.java
  src/main/java/server/poptato/todo/infra/repository/JpaRoutineRepository.java
  src/main/java/server/poptato/todo/infra/repository/impl/RoutineRepositoryImpl.java
Labels: 📄 docs, 🚀 feat, 🚨 fix, 😵‍💫 SANGHO

#147 ILLDAN-136 [test] : Emoji 도메인, Repository 관련 테스트를 작성한다
  build.gradle
  src/test/java/server/poptato/auth/application/AuthServiceTest.java
  src/test/java/server/poptato/configuration/RepositoryTestConfig.java
  src/test/java/server/poptato/emoji/infra/JpaEmojiRepositoryTest.java
  src/test/java/server/poptato/policy/application/PolicyServiceTest.java
  src/test/resources/application-unittest.yml
Labels: ⚒️ chore, 😄 JAEWOONG, ✅ test
